all:
  hosts:
    vagrant-pihole-01:
      ansible_host: 192.168.56.4
      ansible_port: 22
      priority: 110
      keepalive_role: MASTER
    vagrant-pihole-02:
      ansible_host: 192.168.56.5
      ansible_port: 22
      priority: 100
      keepalive_role: BACKUP
  vars:
    ansible_user: vagrant
    ansible_password: vagrant # only used on first run
    password_lock: false # Change to false if you still wish to login via passwd auth
    ansible_user_home_dir: /home/{{ ansible_user }}
    ansible_python_interpreter: /usr/bin/python3
    github_user_for_ssh_key: steveyminecraft # Change me to required value
    pihole_image: "pihole/pihole:2024.07.0"
    timezone: "Europe/London"
    pihole_environment_variables:
      TZ: "{{ timezone }}"
      FTLCONF_MAXDBDAYS: "180"
      WEBPASSWORD: Intranet # example value, change it and better use ansible-vault
      PIHOLE_DNS_: "1.1.1.1;2606:4700:4700::1111"
      REV_SERVER: "true"
      REV_SERVER_CIDR: "192.168.56.0/24"      
      REV_SERVER_TARGET: "192.168.56.1"
      REV_SERVER_DOMAIN: "vagrant.test"
    pihole_ha_mode: true
    pihole_vip_ipv4: "192.168.56.10/24"
    pihole_vip_ipv6: "fd00::10/64"
    sync_target: "{{ pihole_vip_ipv4.split('/')[0] }}"
    gravity_sync_version: v4.0.7
    dnsmasq_listening: single
    pihole_container_name: pihole
    vagrant_env: true
    docker_users:
      - vagrant