# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Configuration
Vagrant.configure("2") do |config|

  # Global Settings
  vm_settings = {
    box: "bento/rockylinux-9",
    memory: 2048,
    cpus: 4,
    machines: [
      { name: "vagrant-pihole-01", ip: "192.168.56.4" },
      { name: "vagrant-pihole-02", ip: "192.168.56.5" }
    ]
  }

  ### DEFINE SCRIPT ### 
  $script = <<-SCRIPT
  echo I am provisioning...
  date > /etc/vagrant_provisioned_at
  # PUT EXTRA OPTIONS IN HERE
  SCRIPT

  # Provider Settings
  config.vm.provider "virtualbox" do |v|
    v.memory = vm_settings[:memory]
    v.cpus = vm_settings[:cpus]
  end

  # Vbguest auto-update but only if plugin is present #Defaulted to off
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  # Define VMs
  vm_settings[:machines].each do |machine|
    config.vm.define machine[:name] do |vm|
      vm.vm.hostname = machine[:name]
      vm.vm.box = vm_settings[:box]
      vm.vm.box_check_update = false
      vm.vm.network "private_network", ip: machine[:ip]
      vm.vm.provision "shell", inline: $script

      # Cleanup known_hosts entry after destruction
      vm.trigger.after :destroy do |trigger|
        trigger.info = "Removing known_hosts entry for #{machine[:name]}"
        trigger.run = { inline: "ssh-keygen -R #{machine[:ip]}" }
      end
    end
  end
end