# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
	v.memory = 2048
  	v.cpus = 2
  end

  ##### DEFINE VM #####\
  config.vm.define "vagrant-pihole-01" do |config|
    config.vm.hostname = 'vagrant-pihole-01'
    #config.vm.box = "bento/ubuntu-24.04"
    config.vm.box = "bento/rockylinux-9"
    config.vm.box_check_update = true
    config.vm.network "private_network", ip: "192.168.56.4"
  end

  config.vm.define "vagrant-pihole-02" do |config|
    config.vm.hostname = 'vagrant-pihole-02'
    #config.vm.box = "bento/ubuntu-24.04"
    config.vm.box = "bento/rockylinux-9"
    config.vm.box_check_update = true
    config.vm.network "private_network", ip: "192.168.56.5"
  end
end
